### ISSUE TITLE
Create New Puppets for Wechaty

### ISSUE THREAD

**Issue by huan** [wechaty/wechaty#1167]
Before v0.15, we only have one Puppet: Web.

From v0.16, we will be able to support multiple puppets that can be selected when starting Wechaty.

Work In Progress...

Details at Wiki Page: https://github.com/wechaty/wechaty/wiki/Puppet

### New Puppet List

- [x] AbstractPuppet: <https://github.com/wechaty/wechaty-puppet>
- [x] PuppetPadChat: #1249 [Alpha Testers](https://github.com/wechaty/wechaty/issues/1296)
- [x] PuppetPuppeteer(the former _PuppetWeb_): #790 
- [x] PuppetMock: #1177
- [x] PuppetWechat4U: #69
- [x] PuppetIoscat: #1528 [Alpha Testers](https://github.com/wechaty/wechaty/issues/1530)
- [x] PuppetPadpro: #1629 
- [ ] PuppetDing: #1683 
- [x] PuppetWechatWork: #1684 
- [ ] PuppetWeibo: #1685
- [x] PuppetService: #1237
- [ ] PuppetAndroid: #400 
- [x] PuppetWin32: #1191
- [x] PuppetOfficialAccount: #1016 
- [ ] PuppetEmail: #??? :D 
- [ ] PuppetSms: #??? :D 
- [x] PuppetQQ: https://github.com/wechaty/summer/issues/81
- [ ] PuppetMatrix: #1774

**Comment by zixia** [comment]
New Puppets are in the alpha stage now! 

See: #1296

**Comment by zixia** [comment]
Close this issue because we almost get all we want from the new puppets!

**Comment by zixia** [comment]
Open for new Puppet: Ioscat #1528
