### ISSUE TITLE
Feature Request: Message Could Mention All Members in Room but Not Announcement.

### ISSUE THREAD

**Issue by su-chang** [wechaty/wechaty#2394]
## Background
When we want to send message which could mention all members in the room, we could set room announcement for it.

But it will stay on the board until the next new announcement coming. If this message is not so much important to set on the board, we really need some other method to suit this case.

For example, mention all members only. Just like:

`@all hello, everybody here.`

And this feature has been supported in `WeCom` now.

### Design One
Above all, I'd like to make it into method `room.say()` and could transfer a special params like: `[ @all ]`.

**Interface**
```ts
async say (sayable: Sayable | TemplateStringsArray, ...varList: unknown[]): Promise<void | MessageInterface>
```

**Example**
```ts
const room = wechaty.Room.find({ name: 'Mention all members room' })
await room.say('hello, everybody here.', ...[ '@all' ])
```

This design in common sense. But will process with the special params `[ '@all' ]`, and with a little trouble for some puppets adaption.

### Design Two
Another way to support it.

**Interface**
```ts
async announce (text: string, pin: boolean = true) : Promise<void>
```

> Maybe the params `pin` could be replaced by a better name.

**Example**
```ts
const room = wechaty.Room.find({ name: 'Mention all members room' })
await room.announce('hello, everybody here.', false) // would regard it as text message with mention only
```

This design could make use and implement it easily. If you don't want to set an announcement, just transfer a `false` params. It will be a text message which could only mention all members in room.

## Todo List
- [ ] PR in wechaty
- [ ] PR in puppet
- [ ] PR in puppet-service
- [ ] PR in grpc

**Comment by windmemory** [comment]
I would like to vote design one, seems like that one is more common across different IMs.

**Comment by huan** [comment]
I feel design two is more clear to me, and at the same time there will also be no problem across other IMs? (please correct me if I'm wrong @windmemory )

@su-chang Please feel free to go ahead to create a PR to demonstrate your design two, let's continue discussing based on the PR, and thank you very much for your new feature RFC!

**Comment by windmemory** [comment]
I think the main problem for design two is that, the @all symbol could show up in any position inside a message, not only at the beginning, but also somewhere in the middle. So if we do design two, the method will lack of the ability to explicitly set the position of @all.

**Comment by huan** [comment]
Could we just put a string `@all` in the content?

Like:

```ts
room.announce('Attention! @all Please read: ...', false)
```

Does that fulfill your requirement?

**Comment by windmemory** [comment]
I think this might cause unintended bugs to Wechaty. What if the user call this function like this:
```
room.announce('Attention! @all Please read: ...', true)
```

Currently it is not possible to create such announcement with @all in the middle of the message, but this is allowed by the method. And actually @all message is just a message, not an announcement, we should keep that two concepts clearly separated.

**Comment by huan** [comment]
I don't think it will be an issue because the Wechaty will not care about the @ in the message string.

Users can put whatever they want into that string, and wechaty will just pass it as a string.

Is there anything I have missed?

**Comment by windmemory** [comment]
This is passing a wrong message to the developer, which is saying: announcement would support @all in the middle of the message, but actually it is not.
When we design the API, we should also consider about whether the API is properly aligned with the real functionality.

Besides the reason above, the most important reason is:
#### **`announcement` ≠ `@all message`**
This is a common design across different IMs, like Lark we are using the most during our work, setting an announcement does not require to publish this to the room, but when you want to announce an announcement, you can manually publish it.
![image](https://user-images.githubusercontent.com/6801292/160996920-3257a3dd-675d-4d4e-ba8d-1853d56af570.png)
And after you publish the announcement, it is not a regular message, but a announcement message, like this:
![image](https://user-images.githubusercontent.com/6801292/160997025-a0951f83-d07a-46ea-bf94-b28136252225.png)
And here is the `@all message` looks like:
![image](https://user-images.githubusercontent.com/6801292/160997103-69174823-a8a7-482d-8a64-ff2654685071.png)

So I think if we merge the two concepts, `annoucement` and `@all message` together, it will introduce a lot of troubles in the future, this is why I don't like the design two, but prefer to implement design one.

**Comment by huan** [comment]
I think I got your idea.

So let's just ignore the `@all` for now, and focus on the improvements of the `announce()` methods.

Does this look good to you?

**Comment by windmemory** [comment]
I think we are discussing about how to implement `@all` feature here, so I don't think we could ignore the `@all` for now.

Shall we continue discuss the `@all` feature here?

**Comment by hcfw007** [comment]
I like design one because it mentioning all is sending a message, not setting a room announcement. So to use room.say is much better than room. announce.

**Comment by hcfw007** [comment]
@huan please check out my draft PR at your convenience. I think this design requires no change in wechaty-puppet and wechaty-grpc (as we pass mention id list as string[], and '@all' can be regarded as a special id).

**Comment by huan** [comment]
Thanks for the PR. I'll think about the magic string '@all' for some time.

Basically, I do not like magic strings. (An alternate would use a `Symbol`, but it should be not used at the user end because it's not serializable)

**Comment by hcfw007** [comment]
I don't like it either. Perhaps we chan create a special Contact Instance representing 'all contacts'? Or define a static string in wechaty-puppet?

**Comment by hcfw007** [comment]
@huan Have you thought it through? We may also add a method like `room.SayToAll('something')`,  however if we want to make the '@all' string in the middle of the text (via templateStringArray), we still need to use `room.say`. As we pass contact ids to puppet implementation, if we don't want to change current puppet.sendMessageText design, using this magic string seems inevitable.

**Comment by huan** [comment]
> Perhaps we can create a special Contact Instance representing 'all contacts'? Or define a static string in wechaty-puppet?

Neither the special contact nor static string in puppet make me feel comfortable.

> add a method like room.SayToAll('something')

Adding a method for this tiny feature looks like a overkill

> async announce (text: string, pin: boolean = true)

How do you think about the design 2? @su-chang raise the propose and I feel it is acceptable for me.

**Comment by hcfw007** [comment]
I don't know...After all we are sending a text message in a room, use announce doesn't make much sense...

**Comment by hcfw007** [comment]
However it does make this problem much easier. We don't even have to handle any other '@' in the string. (e.g. '@all @someone Something just happened!'.). We can pass the string as it is.
If you like design 2 better, I can open a PR for that.

**Comment by huan** [comment]
> We don't even have to handle any other '@' in the string. (e.g. '@ALL @Someone Something just happened!'.). We can pass the string as it is.

That's the point!

Please feel free to open an PR and let's continue discussing based in it.

**Comment by hcfw007** [comment]
Hold on a moment before I start this PR cause I just found that you can @someone more than once in both Lark and Whatsapp. (and that effects the content, not just the notification).
e.g.:
1. Lark:
![image](https://user-images.githubusercontent.com/13669999/165430052-32057f9d-2f04-4300-ab94-2d13bb1d07de.png)
2. Whatsapp:
![image](https://user-images.githubusercontent.com/13669999/165430416-e2bdd8bc-15f2-4adc-8b38-7e898fe171d4.png)

Any idea about implementing that in `room.anounce`? We can do that in `room.say()` because '@all' is just a regular member in mention list.

**Comment by hcfw007** [comment]
@huan ping

**Comment by huan** [comment]
I can not understand what's the point of mentioning one user name twice in one message?

And could you explain why "@ALL is just a regular member in mention list"? What do you mean a "regular"?

**Comment by hcfw007** [comment]
>  I can not understand what's the point of mentioning one user name twice in one message?
e.g. there is a new member in the company, and we want to give the new comer a warm welcome:
'@ALL Attention everyone, @Someone has just joined us, please show your passion and give him a warm welcome'
There can be more scenarios, but I believe what really matters is: IM support this kind of usage, and we should not the stop the user from using that.

> And could you explain why "https://github.com/ALL is just a regular member in mention list"? What do you mean a "regular"?
I mean in this mentionList Array, '@ALL' is just like any other member (Contact instances), it can show up in any position of the text, there can be more than one '@ALL', etc.

**Comment by huan** [comment]
Could you please convert this requirement into a end user source code to express it?

I think the current design will not stop you doing them.

**Comment by hcfw007** [comment]
Take this as example:
![image](https://user-images.githubusercontent.com/13669999/167242080-ce146e55-4139-472b-8cfe-cda38abfcd99.png)

1. with magic-string approach:
```ts
const room = bot.room.find({ name: 'dev' })
const contact = bot.contact.find({ name: '王楠' })
room.say(['', ',', '刚刚修复了一个bug'], '@all', contact) // i'm not sure if I have used templateStringArray correctly
```

2. with announce approach:
```ts
const room = bot.room.find({ name: 'dev' })
const contact = bot.contact.find({ name: '王楠' })
room. announce('@王楠刚刚修复了一个bug', false)
```


The thing is, the '@王楠' in the second approach will not be a real mention. You can not click to get the contact nor the text will be blue in Lark.

**Comment by huan** [comment]
> room.say(['', ',', '刚刚修复了一个bug'], '@all', contact) // i'm not sure if I have used templateStringArray correctly

No, the above usage of the `TemplateString` is definitely NOT correct.

The correct usage is:

```ts
room.say`@all ${contact} 刚刚修复了一个bug`
```

I have discussed "Tagged Templates transform a Template String" with @wechaty/juzi before about the `TemplateArrayString`, see:

- https://github.com/wechaty/wechaty/issues/1718#issuecomment-472937224
- https://github.com/wechaty/wechaty/pull/1729#issuecomment-478158505
- https://github.com/wechaty/wechaty/issues/1893#issuecomment-569494960

**Comment by hcfw007** [comment]
@huan I have updated my example.
The main point is: although it's a rare occasion, it's supported by multiple IMs, and we should not block user from using it.
(by it I mean mention someone while also mentioning everyone)

**Comment by huan** [comment]
The magic string proposal is not a good idea so let's not use it as possible as we can.

According to your example code, I think the below code is what you need:

```ts
room. announce`@所有人 ${contact} 刚刚修复了一个bug`
```

BTW: I think this is a Lark-related rich feature? Is the Wechaty Puppet Lark able to be used in production now?

**Comment by hcfw007** [comment]
> The magic string proposal is not a good idea so let's not use it as possible as we can.
> 
> According to your example code, I think the below code is what you need:
> 
> ```ts
> room. announce`@所有人 ${contact} 刚刚修复了一个bug`
> ```
> 
> BTW: I think this is a Lark-related rich feature? Is the Wechaty Puppet Lark able to be used in production now?

This will require room.announce to accept templateStringArray also. This does solve the problem so I'm happy with it.

For Puppet-Lark, I don't think so. But whatsapp have similar feature, you can mention the same person more than once in the one message.

**Comment by huan** [comment]
> This will require room.announce to accept templateStringArray also. This does solve the problem so I'm happy with it.

Glad to know.

Then the next question will be how can we pass another argument to the TemplateStringArray method.

**Comment by hcfw007** [comment]
> Then the next question will be how can we pass another argument to the TemplateStringArray method.

Also how should we pass this to the puppet. puppet.sendMessageText() accepts ContactId[], and if we pass '@all' we are kinda using magic string again.

**Comment by huan** [comment]
> Also how should we pass this to the puppet. puppet.sendMessageText() accepts ContactId[], 

I think we should use `puppet.roomAnnounce()` instead of the `sendMessageText()`?

> if we pass '@ALL' we are kinda using magic string again.

I think this is just a `string` instead of a `magic string`.

**Comment by hcfw007** [comment]
Maybe we can treat all TemplateStringArray room announces as a mention all message.
Because any mention will be degraded to regular text in IMs I use, there is no point to @someone when setting announcements.

**Comment by huan** [comment]
> Maybe we can treat all TemplateStringArray room announces as a mention all message.

Brilliant! 

I agree with you and feel this is a perfect solution.

**Comment by hcfw007** [comment]
@huan can you check out this draft https://github.com/wechaty/wechaty/pull/2418?
It's a bit wierd since if we want to mention all while mentioning other people, we have to pass one more parameter: mentionList.

**Comment by hcfw007** [comment]
After discussion in Wechaty Community Meeting (brief [here](https://docs.google.com/document/d/1fVCk8qRYc4RKGMf2UY5HOe07hEhPUOpGC34v88GEFJg/edit#heading=h.si1xxj2xji7f))
We have dicided to achieve @all message by mentioning the room.
TODO:
1. In wechaty, we should allow passing RoomInterface into mention list and say with template string array.
2. Split string into string array in wechaty-grpc to match @ with position in text.
3. Create a new messageSendText method to send mention message with contact Id instead of @+name.
